version: 2

jobs:
   alpine:
      docker:
         - image: alpine:latest
      steps:
         - checkout
         - run: |
              echo "Hello"
              apk update
              apk add libedit-dev zlib-dev m4 make cmake fmt-dev git boost-dev openmpi-dev llvm flex bison gcc g++ patch numactl-dev
              git clone https://github.com/asyncvlsi/actflow
              cd actflow
              git submodule update --init --recursive
              mkdir /usr/local/cad
              export ACT_HOME=/usr/local/cad
              ./build
              uname -a

   alma:
      docker:
         - image: almalinux:8.7
      steps:
         - checkout
         - run: |
              yum install -y 'dnf-command(config-manager)'
              yum config-manager --set-enabled powertools -y
              yum install -y gcc gcc-c++ diffutils make libedit-devel zlib-devel m4 cmake git libboost-all-dev openmpi-devel llvm flex bison patch which
              git clone https://github.com/asyncvlsi/actflow
              cd actflow
              git submodule update --init --recursive
              mkdir /usr/local/cad
              export ACT_HOME=/usr/local/cad
              ./build

   rocky:
      docker:
         - image: rockylinux:9
      steps:
         - checkout
         - run: |
              echo "Hello"
              dnf install -y gcc gcc-c++ diffutils make libedit-devel zlib-devel m4 cmake git boost-devel openmpi-devel llvm flex bison patch 
              git clone https://github.com/fmtlib/fmt
              cd fmt
              mkdir build
              cd build && cmake .. && make && make install
              git clone https://github.com/asyncvlsi/actflow
              cd actflow
              git submodule update --init --recursive
              mkdir /usr/local/cad
              export ACT_HOME=/usr/local/cad
              ./build
              uname -a

   actlib:
      docker:
         - image: rajitmanohar/actlib:latest
      steps:
         - checkout
         - run: |
              echo "Hello!"
              uname -a
              which gcc
   

workflows:
   version: 2
   build:
      jobs:
          - alma
