version: 2

jobs:
   ubuntu18:
     # Ubuntu 18
     docker:
       - image: ubuntu:18.04
     steps:
       - checkout
       - run: 
            echo "Hello"

   centos9:
     docker:
       - image: centos:9
     steps:
       - checkout
       - run:
            echo "Hi"

workflows:
   version: 2
   build:
     jobs: 
        - ubuntu18
        - centos9
