version: 2

jobs:
   alpine:
      docker:
         - image: alpine:latest
      steps:
         - checkout
         - run: |
              echo "Hello"
              aptk update
              apk add libedit zlib m4 make cmake fmt git boost openmpi llvm flex bison gcc g++
              git clone https://github.com/asyncvlsi/actflow
              cd actflow
              git submodule update --init --recursive
              mkdir /usr/local/cad
              export ACT_HOME=/usr/local/cad
              ./build
              uname -a

   actlib:
      docker:
         - image: rajitmanohar/actlib:latest
      steps:
         - checkout
         - run: |
              echo "Hello!"
              uname -a
              which gcc
   

workflows:
   version: 2
   build:
      jobs:
         - alpine
         - actlib
