version: 2

jobs:
   ubuntu:
      docker:
         - image: ubuntu
      steps:
         - checkout
         - run: |
              echo "Hello"
              apt-get -q update -y
              apt-get -q install -y libedit-dev zlib1g-dev m4 build-essential cmake libfmt-dev git cmake libboost-all-dev libopenmpi-dev llvm flex bison
              git clone https://github.com/asyncvlsi/actflow
              cd actflow
              git submodule update --init --recursive
              mkdir /usr/local/cad
              export ACT_HOME=/usr/local/cad
              ./build
              uname -a

   centos9:
      docker:
         - image: cimg/base:2020.01
      steps:
         - checkout
         - run: |
              echo "Hi"
              dnf update -y
              dnf install -y 'dnf-command(config-manager)'
              yum config-manager --set-enabled powertools -y
              dnf install -y gcc gcc-c++ diffutils make libedit-devel zlib-devel m4 flex bison git cmake libfmt-devel libboost-all-devel llvm
              git clone https://github.com/asyncvlsi/actflow
              cd actflow
              git submodule update --init --recursive
              mkdir /usr/local/cad
              export ACT_HOME=/usr/local/cad
              ./build
              uname -a
              lsb_release -a
              
   actlib:
      docker:
         - image: rajitmanohar/actlib:latest
      steps:
         - checkout
         - run: |
              echo "Hello!"
              uname -a
              which gcc
   

workflows:
   version: 2
   build:
      jobs:
         - centos9
         - actlib
